//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int MaQuyen { get; set; }
        public int MaLoaiTK { get; set; }
        public Nullable<bool> KichHoat { get; set; }
    
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
